#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

process.chdir(path.resolve(__dirname, '..'));

require(`../js/battle-dex.js`);
require(`../js/battle-dex-data.js`);
require(`../js/battle.js`);
global.BattleText = require(`../data/text.js`).BattleText;
require(`../js/battle-text-parser.js`);

const parser = new BattleTextParser();

const readline = require('readline');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

rl.on('line', line => {
  process.stdout.write(Battle.extractMessage(line, parser));
});
