#!/usr/bin/env node

/**
 * This script parses index.html and sets the version query string of each
 * resource to be the MD5 hash of that resource.
 */

const fs = require('fs');
const crypto = require('crypto');

process.chdir(__dirname);

function updateIndex() {
	let indexContents = fs.readFileSync('theme/wrapper.inc.template.php', {encoding: 'utf8'});

	// add hashes to js and css files
	process.stdout.write("Updating hashes... ");
	indexContents = indexContents.replace(/(src|href)="\/(.*?)\?[a-z0-9]*?"/g, function (a, b, c) {
		let hash = Math.random(); // just in case creating the hash fails
		try {
			var filepath = c;
			if (c.includes('/play.pokemonshowdown.com/')) {
				const filename = c.replace('/play.pokemonshowdown.com/', '');
				filepath = '../' + filename;
			}
			const fstr = fs.readFileSync(filepath, {encoding: 'utf8'});
			hash = crypto.createHash('md5').update(fstr).digest('hex').substr(0, 8);
		} catch (e) {}

		return b + '="/' + c + '?' + hash + '"';
	});
	console.log("DONE");

	process.stdout.write("Writing new `wrapper.inc.php` file... ");
	fs.writeFileSync('theme/wrapper.inc.php', indexContents);
	console.log("DONE");
}

updateIndex();
