#!/usr/bin/env node
const {exec} = require('child_process');

exec(
	'npx babel api --out-dir .api-dist --config-file ./api/.babelrc ' +
	'--ignore "*/node_modules/*" --extensions ".ts"',
	(err, stdout) => err ? console.error(err) : console.log(stdout)
);
